# Generated by Django 2.0.5 on 2018-06-01 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.CharField(max_length=1024)),
                ('notes', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='dictionary',
            name='soundFileName',
        ),
        migrations.RemoveField(
            model_name='dictionary',
            name='translation',
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='original',
            field=models.CharField(max_length=1024),
        ),
        migrations.AddField(
            model_name='translation',
            name='original',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Dictionary'),
        ),
    ]
