# Generated by Django 2.0.5 on 2018-06-01 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20180601_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwords',
            name='translation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Translation'),
        ),
    ]
