# Generated by Django 2.0.5 on 2018-06-01 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_userwords_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwords',
            name='notes',
        ),
    ]
