# Generated by Django 2.0.5 on 2018-06-03 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_moderndictionary_moderntranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversalDictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='UniversalTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.CharField(max_length=1024)),
                ('notes', models.CharField(max_length=200)),
                ('original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.UniversalDictionary')),
            ],
        ),
    ]
