# Generated by Django 2.0.5 on 2018-06-03 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_universaldictionary_universaltranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwords',
            name='translation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.UniversalTranslation'),
        ),
    ]
