# Generated by Django 2.0.5 on 2018-06-03 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20180603_1744'),
    ]

    operations = [
    ]
