# Generated by Django 2.0.5 on 2018-06-07 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20180603_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversalSounds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soundfile', models.CharField(max_length=200)),
                ('original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.UniversalDictionary')),
            ],
        ),
    ]
